import { ReportExplainer } from "@/components/report/ReportExplainer";
import { ReportHero } from "@/components/report/ReportHero";
import { FindingsSection } from "@/components/report/FindingsSection";
import { OpportunitiesSection } from "@/components/report/OpportunitiesSection";
import { RoadmapSection } from "@/components/report/RoadmapSection";
import { StickyDecisionBar } from "@/components/report/StickyDecisionBar";
import type { Sprint, SprintProgress, Opportunity, SynthesisMemo } from "@/lib/types";
import type { WorkflowMapView } from "@/services/synthesis/workflows/types";

/**
 * The discovery report body, shared by the manager/sponsor report and the
 * Twistag read-only report. The page owns the toolbar + data fetch; this owns
 * the `<article>`. Pass `opportunityHref` to link opportunities (manager/sponsor
 * view) and `isSponsor` to label the CTA; omit both for the read-only view.
 */
export function ReportArticle({
  sprint,
  progress,
  opps,
  memo,
  workflowMaps = [],
  opportunityHref,
  isSponsor = false,
}: {
  sprint: Sprint;
  progress: SprintProgress;
  opps: Opportunity[];
  memo?: SynthesisMemo | null;
  workflowMaps?: WorkflowMapView[];
  opportunityHref?: (id: string) => string;
  isSponsor?: boolean;
}) {
  const currency = sprint.tenantCurrency;
  return (
    <article className="mx-auto max-w-3xl px-6 py-10">
      <StickyDecisionBar opps={opps} currency={currency} opportunityHref={opportunityHref} isSponsor={isSponsor} />

      <ReportHero
        sprint={sprint}
        progress={progress}
        opps={opps}
        currency={currency}
        opportunityHref={opportunityHref}
        isSponsor={isSponsor}
      />

      {memo && memo.openingNarrative ? (
        <Section title="In short">
          <p>{memo.openingNarrative}</p>
          {memo.recommendedNextStep ? (
            <p><strong>Recommended next step. </strong>{memo.recommendedNextStep}</p>
          ) : null}
        </Section>
      ) : null}

      <FindingsSection maps={workflowMaps} />

      <OpportunitiesSection opps={opps} maps={workflowMaps} currency={currency} href={opportunityHref} />

      <RoadmapSection opps={opps} />

      <Section title="How we got here">
        <p>
          Atlas runs discovery as conversation, not workshops. Each participant completed up to four short sessions on their own schedule. An extraction pass lifted concrete moments — bottlenecks, workarounds, handoffs — attributed to the contributor by name and role, then clustered and scored across five dimensions.
        </p>
      </Section>

      <Section title="What happens next">
        <p>
          Each opportunity links to its full evidence and a pre-drafted SOW. Approve one and the Twistag engagement team aligns scope within 48 hours; the first ship typically lands in 2–4 weeks.
        </p>
      </Section>

      <div className="mt-8"><ReportExplainer /></div>

      <footer className="mt-10 border-t border-border pt-6 text-xs text-text-3">
        Generated by Atlas · {sprint.startDate} – {sprint.endDate} · Built by Twistag. Quotes attributed to contributors by name and role.
      </footer>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="mb-3 text-2xl font-semibold tracking-tight">{title}</h2>
      <div className="space-y-3 text-md leading-relaxed text-text-2 [&_strong]:font-semibold [&_strong]:text-text">
        {children}
      </div>
    </section>
  );
}
